### ISSUE TITLE
incorrect date at 'blog' page

### ISSUE THREAD

**Issue by ViniciusTheCoder** [imyuanli/next-blog#9]
my blog page is updating the article post date every single day, i'm not understanding:

![image](https://github.com/imyuanli/next-blog/assets/100241274/1b365aad-6d64-413b-bf63-ad1253a91a7d)

source code: https://github.com/ViniciusTheCoder/vinicius.dev

**Comment by imyuanli** [comment]
Sorry, I have been busy with other things before. I have fixed this issue and added many new things in the latest version. You can try updating the code to the latest version.

**Comment by ViniciusTheCoder** [comment]
thanksss :D, in the meantime I ended up creating a fix in my repository kekeke, but appreciate it anyway

**Comment by imyuanli** [comment]
这是自动回复的邮件。您好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by imyuanli** [comment]
> 谢谢:D，与此同时，我最终在我的存储库 kekeke 中创建了一个修复程序，但无论如何都很感激
Thank you again, then I will close the issue first. If you have any questions, please feel free to bring up the issue with me again
